import {chmod,mkdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {defaultConfig} from '../src/storage/config.ts';
const root=await mkdtemp(join(tmpdir(),'s42-binary-smoke-')),source=resolve(Bun.argv[2]??'dist/s42-agent-0.1.1-linux-x64'),binary=join(root,'s42-agent');await Bun.write(binary,Bun.file(source));await chmod(binary,0o755);await Bun.write(join(root,'code.ts'),'const value = 1;');
await mkdir(join(root,'smoke'));await Bun.write(join(root,'smoke/SKILL.md'),'---\nname: smoke\ndescription: Smoke test coding\n---\nPreserve code and report checked results.');
let calls=0,mcpEffects=0,skillLoaded=false,output='';
const mcp=Bun.serve({port:0,async fetch(req){const p=await req.json() as any;return Response.json({jsonrpc:'2.0',id:p.id,result:p.method==='server/discover'?{supportedVersions:['2026-07-28'],capabilities:{tools:{}}}:p.method==='tools/list'?{tools:[{name:'check',description:'Smoke check',inputSchema:{type:'object',properties:{}}}]}:{content:[{type:'text',text:'BINARY_MCP '+(++mcpEffects)}]}});}});
const llm=Bun.serve({port:0,async fetch(req){if(req.method!=='POST')return new Response('Fixture has no discovery metadata',{status:404});const p=await req.json() as any;calls++;skillLoaded=p.messages[0].content.includes('Preserve code');const mcpName=p.tools.find((t:any)=>t.function.name.startsWith('mcp_')).function.name;
 const definitions=[{name:'read',arguments:'{"path":"code.ts"}'},{name:mcpName,arguments:'{}'},{name:'edit',arguments:'{"path":"code.ts","oldText":"value = 1","newText":"value = 2"}'},{name:'shell',arguments:'{"command":"test -f code.ts && printf verified"}'}];const call=definitions[calls-1];const delta=call?{tool_calls:[{index:0,id:'smoke-'+calls,function:call}]}:{content:'BINARY_COMPLETE'};
 return new Response(`data: ${JSON.stringify({choices:[{delta,finish_reason:call?'tool_calls':'stop'}]})}\n\ndata: [DONE]\n\n`);
}});
const config=defaultConfig();config.providers[0]!.baseUrl=`http://127.0.0.1:${llm.port}/v1`;config.providers[0]!.models=[{id:'smoke',name:'Smoke',contextWindow:32000,maxOutputTokens:1000,capabilities:{tools:true,images:false}}];config.defaults.modelId='smoke';config.mcpServers=[{id:'mcp',name:'Smoke',enabled:true,transport:'http',url:`http://127.0.0.1:${mcp.port}`}];config.skills=[{id:'smoke',name:'smoke',path:join(root,'smoke/SKILL.md'),enabled:true}];await Bun.write(join(root,'config.json'),JSON.stringify(config));
const terminal=new Bun.Terminal({cols:80,rows:24,data:(_,bytes)=>output+=new TextDecoder().decode(bytes)});let child:Bun.Subprocess;
async function until(check:()=>boolean){const deadline=Date.now()+5000;while(!check()){if(Date.now()>deadline)throw new Error('Timeout smoke '+output.slice(-1000));await Bun.sleep(2);}}
try{const env={TERM:'xterm-256color',PATH:'/nonexistent'};const versionProcess=Bun.spawn([binary,'--version'],{cwd:root,env,stdout:'pipe',stderr:'pipe'});const version=(await new Response(versionProcess.stdout).text()).trim();if(await versionProcess.exited!==0)throw new Error('Version smoke failed');
 child=Bun.spawn([binary,'--config',join(root,'config.json'),'--cwd',root],{cwd:root,env,terminal});await until(()=>output.includes('Prompt'));terminal.write('/skill smoke check coding\r');await until(()=>output.includes('BINARY_COMPLETE'));terminal.write('\x11');if(await child.exited!==0)throw new Error('Exit smoke failed');await until(()=>output.includes('\x1b[?1049l'));if(!skillLoaded||mcpEffects!==1||await Bun.file(join(root,'code.ts')).text()!=='const value = 2;')throw new Error('Effects not verified');
 const bytes=await Bun.file(binary).arrayBuffer();const result={at:new Date().toISOString(),platform:process.platform,arch:process.arch,version,sha256:new Bun.CryptoHasher('sha256').update(bytes).digest('hex'),calls,mcpEffects,skillLoaded,edited:true,shell:true,restored:true,cwd:'temporary outside checkout',PATH:'/nonexistent',limits:'Host Bun exists for fixture/PTY driver; agent executable invoked directly without Bun/Node or checkout files; LLM/MCP are external HTTP fixtures; no physical mouse/drop'};await Bun.write(resolve(import.meta.dir,'../dist/binary-smoke.json'),JSON.stringify(result,null,2)+'\n');for(const manifestPath of [resolve(import.meta.dir,'../dist/build-targets.json')])if(await Bun.file(manifestPath).exists()){const manifest=await Bun.file(manifestPath).json();const entry=manifest.entries.find((e:any)=>e.sha256===result.sha256);if(entry){entry.runtimeValidated=true;entry.runtimeEvidence='binary-smoke.json';await Bun.write(manifestPath,JSON.stringify(manifest,null,2)+'\n');}}console.log(JSON.stringify(result));
}finally{try{child!.kill();}catch{}terminal.close();llm.stop(true);mcp.stop(true);await rm(root,{recursive:true,force:true});}
